services:
  downloader-bot:
    image: ghcr.io/mak5er/downloader-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - downloader_downloads:/app/downloads
      - downloader_log:/app/log
    env_file: .env
    container_name: downloader-bot
    restart: always

volumes:
  downloader_downloads:
  downloader_log:
