services:
  downloader-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mak5er/downloader-bot
    volumes:
      - .:/app
    env_file: .env
    container_name: downloader-bot
    restart: always
